version: "3.9"
name: quilibrium
services:
  node:
    # created with version v1.4.0 (https://github.com/QuilibriumNetwork/ceremonyclient/commit/7ad553fd62fbabde1afb1c782afc36f8360f243e)
    image: ccrayzeth/quilibrium:v1.4.0
    restart: unless-stopped
    # TODO(ccrayz): Enable if needed
    # deploy:
    #   resources:
    #     limits:
    #       memory: 32G
    #     reservations:
    #       cpus: 12
    #       memory: 16G
    environment:
      - DEFAULT_LISTEN_GRPC_MULTIADDR=/ip4/0.0.0.0/tcp/8337
      - DEFAULT_LISTEN_REST_MULTIADDR=/ip4/0.0.0.0/tcp/8338
      - DEFAULT_STATS_MULTIADDR=/dns/stats.quilibrium.com/tcp/443
    ports:
      - '8336:8336/udp' # p2p
      - '8337:8337/tcp' # gRPC
      - '8338:8338/tcp' # REST
    volumes:
      - ./.config:/opt/ceremonyclient/node/.config
    stop_grace_period: 100s
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
