version: "3.9"

services:
  avail:
    container_name: avail
    image: availj/avail:${AVAIL_NODE_VERSION:-v1.10.0.0}
    command:
      - --chain=goldberg
      - --name=${AVAIL_NODE_NAME}
      - -d
      - /da/state
    ports:
      - 30333:30333
      - 9615:9615
      - 9944:9944
    volumes:
      - ./state:/da/state:rw
    restart: unless-stopped
    stop_grace_period: 100s
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
